function tProp = turbineArrayProperties()
%% Return location and type of the turbines

% Foot position of the turbine x,y,z (NOT nacelle position, Ground level!)
tProp.Pos = [...
            600  2400 0;...     % T0
            1500 2400 0;...     % T1
            2400 2400 0;...     % T2
            600  1500 0;...     % T3
            1500 1500 0;...     % T4
            2400 1500 0;...     % T5
            600  600  0;...     % T6
            1500 600  0;...     % T7
            2400 600  0;...     % T8
            ]; 

% Turbine type, the parameters are stored centralized in
% Data/TurbineData/getTurbineData.m
tProp.Type = {...
            'DTU 10MW',...
            'DTU 10MW',...
            'DTU 10MW',...
            'DTU 10MW',...
            'DTU 10MW',...
            'DTU 10MW',...
            'DTU 10MW',...
            'DTU 10MW',...
            'DTU 10MW'};
      
% Initial world orientation of the Wind Turbine. Direction is 
% Orthogonal for wind from

% Has to fit the turbine states structure of the selected FLORIS model (see
% States.m), Gaussian: 'a','yaw'(deg,counter-clockwise,relative),'TI'
tProp.Init_States = [...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    0.33 0 0.06; ...
    ];

% NOTE ON THE TURBINE ORIENTATION, THE YAW ANGLE AND THE WIND DIRECTION
%   The wind direction and the turbine orientation are clockwise defined,
%   the yaw angle is the result of 
%       wind direction - orientation = yaw angle
%   Thus, the yaw angle is defined in clockwise direction.
%   Wind from -x to +x has the wind direction 270 deg.
%   Wind from +y to -y has the wind direction 0 / 360 deg.
end