function HKN2019FugroMetOceanBuoys = importHKNData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HKN20190815FUGROMETOCEANBUOYSHKNAWINDRESOURCESPEEDDIRECTIONTIST =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  HKN20190815FUGROMETOCEANBUOYSHKNAWINDRESOURCESPEEDDIRECTIONTIST =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  HKN2019FugroMetOceanBuoys = importfile("/Users/marcusbecker/surfdrive/PhD_Surf/01_Research/01_FLORIDyn/20_Data/05_HKN_Fugro/Processed-data-HKNA/HKN_20190815_Fugro_MetOcean Buoys HKNA WindResourceSpeedDirectionTIStat_F.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Jun-2023 15:57:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 37);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["TIMESTAMPISO8601UTC", "WindDir004mDeg", "WindDir030mDeg", "WindDir040mDeg", "WindDir040m_refDeg", "WindDir060mDeg", "WindDir080mDeg", "WindDir100mDeg", "WindDir120mDeg", "WindDir140mDeg", "WindDir160mDeg", "WindDir180mDeg", "WindDir200mDeg", "WindGust004mMs", "WindSpeed004mMs", "WindSpeed030mhMs", "WindSpeed040mhMs", "WindSpeed040m_refhMs", "WindSpeed060mhMs", "WindSpeed080mhMs", "WindSpeed100mhMs", "WindSpeed120mhMs", "WindSpeed140mhMs", "WindSpeed160mhMs", "WindSpeed180mhMs", "WindSpeed200mhMs", "TI030m", "TI040m", "TI040mRef", "TI060m", "TI080m", "TI100m", "TI120m", "TI140m", "TI160m", "TI180m", "TI200m"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TIMESTAMPISO8601UTC", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "TIMESTAMPISO8601UTC", "EmptyFieldRule", "auto");

% Import the data
HKN2019FugroMetOceanBuoys = readtable(filename, opts);

end