function ccoptimizedangles = importFLORISAngles(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CCOPTIMIZEDANGLES = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CCOPTIMIZEDANGLES = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ccoptimizedangles = importFLORISAngles("/Users/marcusbecker/surfdrive/PhD_Surf/01_Research/01_FLORIDyn/20_Data/05_HKN_Fugro/10_T Optimized Angles/cc_optimized_angles.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Jun-2023 12:55:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "wind_direction", "wind_speed", "turbulence_intensity", "yaw_angles_opt", "Var6", "Var7"];
opts.SelectedVariableNames = ["wind_direction", "wind_speed", "turbulence_intensity", "yaw_angles_opt"];
opts.VariableTypes = ["string", "double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "yaw_angles_opt", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "yaw_angles_opt", "Var6", "Var7"], "EmptyFieldRule", "auto");

% Import the data
ccoptimizedangles = readtable(filename, opts);

end