% Links to the specific controller file which is in use
addpath(strcat('.',filesep,'ClosedLoopControl',filesep, ...
    'Strategy',filesep,CLC.Con.Strategy))
addpath(strcat('.',filesep,'ClosedLoopControl',filesep, ...
    'CostFunction',filesep,CLC.Con.CostFunction))
addpath(strcat('.',filesep,'ClosedLoopControl',filesep, ...
    'PredictWind',filesep,CLC.Con.WindPrediction))
addpath(strcat('.',filesep,'ClosedLoopControl',filesep,'Visualization'))