function time_dir_uv_199m = importfile_ZephIR(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ZEPHIRWINDLIDARBSA1S202002150000202002152350V1 = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as a table.
%
%  ZEPHIRWINDLIDARBSA1S202002150000202002152350V1 = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ZephIRwindlidarBSA1s202002150000202002152350v1 = importfile("/Users/MarcusWork/Downloads/ZephIR_windlidar_BSA_1s_202002150000_202002152350_v1.CSV", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jun-2023 11:09:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 53);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "TimeAndDate", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "WindDirectiondegAt119m", "HorizontalWindSpeedmsAt119m", "VerticalWindSpeedmsAt119m", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53"];
opts.SelectedVariableNames = ["TimeAndDate", "WindDirectiondegAt119m", "HorizontalWindSpeedmsAt119m", "VerticalWindSpeedmsAt119m"];
opts.VariableTypes = ["string", "datetime", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TimeAndDate", "InputFormat", "dd/MM/uuuu HH:mm:ss");
opts = setvaropts(opts, ["WindDirectiondegAt119m", "HorizontalWindSpeedmsAt119m", "VerticalWindSpeedmsAt119m"], "ThousandsSeparator", ",");

% Import the data
time_dir_uv_199m = readtable(filename, opts);

end