% === ADAPTIVE C_xx_Dir CALCULATION WITH DIFFERENT C MATRIX ===
            % =========================================================== %
            % =========================================================== %
%             C_xx_Dir = zeros(T.nOP*T.nT,T.nT);
%             C = zeros(T.nT,T.nOP*T.nT);
%             for iT = 1:T.nT
%                 if sum(EnKF.Interaction{iE,iT}(:,end))==0
%                     % No influence
%                     C(iT,T.StartI(iT)) = 1;
%                     C_xx_Dir(:,iT) = ...
%                         (EnKF.States.Dir - EnKF.States.Dir_mean) * ...
%                         (EnKF.States.Dir(T.StartI(iT),:) - ...
%                         EnKF.States.Dir_mean(T.StartI(iT)))'...
%                         / (EnKF.nE - 1);
%                 else
%                     % Influenced by other turbines
%                     for iiT = 1:size(EnKF.Interaction{iE,iT},1)
%                         C(iT,EnKF.Interaction{iE,iT}(iiT,2)) = ...
%                             EnKF.Interaction{iE,iT}(iiT,3) * ...
%                             EnKF.Interaction{iE,iT}(iiT,6);
%                         C(iT,EnKF.Interaction{iE,iT}(iiT,4)) = ...
%                             EnKF.Interaction{iE,iT}(iiT,5) * ...
%                             EnKF.Interaction{iE,iT}(iiT,6);
%                     end
%                     nze = C(iT,:) ~= 0;
%                     
%                     C_xx_Dir(:,iT) = ...
%                         (EnKF.States.Dir - EnKF.States.Dir_mean) * ...
%                         ((EnKF.States.Dir(nze,:) - EnKF.States.Dir_mean(nze))' * ...
%                         C(iT,nze)') / (EnKF.nE - 1);
%                     
%                     % Slight difference (10^-16) between the two solutions
%                     % C_xx_Vel(:,iT) = ...
%                     %     (EnKF.States.Vel - EnKF.States.Vel_mean) * ...
%                     %     (EnKF.States.Vel - EnKF.States.Vel_mean)'...
%                     %     / (EnKF.nE - 1) * ...
%                     %     C(iT,:)';
%                 end
%             end