% Copyright (C) <2024>, M Becker
%
% List of the contributors to the development of FLORIDyn: see LICENSE file.
% Description and complete License: see LICENSE file.
	
% This program (FLORIDyn) is free software: you can redistribute it and/or modify
% it under the terms of the GNU Affero General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.

% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Affero General Public License for more details.

% You should have received a copy of the GNU Affero General Public License
% along with this program (see COPYING file).  If not, see <https://www.gnu.org/licenses/>.
% ======================================================================= %
% Updated: 16. Dez. 2024, M. Becker
% ======================================================================= %

function CLC_Plot_EnsemblePower_vs_Measured(P_meas, P_ens_prior, P_ens_post, pow_lim)
%CLC_PLOT_ENSEMBLEPOWER_VS_MEASURED Plots the poer generated by each
%turbine as predicted, measured and corrected by the EnKF

figure
hold on
c_pri = [229 86 68]./255;
c_pos = [18 146 199]./255;
for iT = 1:length(P_meas)
    % Plot prior
    % iT - prob
    [N,edges] = histcounts(P_ens_prior(iT,:),10,...
        'Normalization','probability');

    edges = [edges(1:end-1);edges(2:end)]; edges = edges(:);
    N = [N;N]; N = N(:);
    edges = [edges(1); edges; edges(end)];
    N = [0; N; 0];

    patch(iT - N, edges, c_pri, 'EdgeColor','none')
    
    % Plot posterior
    % iT - prob
    [N,edges] = histcounts(P_ens_post(iT,:),10,...
        'Normalization','probability');

    edges = [edges(1:end-1);edges(2:end)]; edges = edges(:);
    N = [N;N]; N = N(:);
    edges = [edges(1); edges; edges(end)];
    N = [0; N; 0];

    patch(iT + N, edges, c_pos, 'EdgeColor','none')

    % Plot Estimate
    scatter(iT,mean(P_ens_post(iT,:)),40,'w','filled',...
        'MarkerEdgeColor','k','LineWidth',1)

    % Plot Measurement
    scatter(iT,P_meas(iT),40,'k','filled',...
        'MarkerEdgeColor','k','Marker','x','LineWidth',2)
    
end
legend({'Prior','Posterior','Estimate','Measurement'})
ylim(pow_lim)
xlim([0,length(P_meas)+1])
ylabel('Power Generated (MW)')
xlabel('Turbine')



end

