function CLC_Plot_EnsemblePower_vs_Measured(P_meas, P_ens_prior, P_ens_post, pow_lim)
%CLC_PLOT_ENSEMBLEPOWER_VS_MEASURED Plots the poer generated by each
%turbine as predicted, measured and corrected by the EnKF

figure
hold on
c_pri = [229 86 68]./255;
c_pos = [18 146 199]./255;
for iT = 1:length(P_meas)
    % Plot prior
    % iT - prob
    [N,edges] = histcounts(P_ens_prior(iT,:),10,...
        'Normalization','probability');

    edges = [edges(1:end-1);edges(2:end)]; edges = edges(:);
    N = [N;N]; N = N(:);
    edges = [edges(1); edges; edges(end)];
    N = [0; N; 0];

    patch(iT - N, edges, c_pri, 'EdgeColor','none')
    
    % Plot posterior
    % iT - prob
    [N,edges] = histcounts(P_ens_post(iT,:),10,...
        'Normalization','probability');

    edges = [edges(1:end-1);edges(2:end)]; edges = edges(:);
    N = [N;N]; N = N(:);
    edges = [edges(1); edges; edges(end)];
    N = [0; N; 0];

    patch(iT + N, edges, c_pos, 'EdgeColor','none')

    % Plot Estimate
    scatter(iT,mean(P_ens_post(iT,:)),40,'w','filled',...
        'MarkerEdgeColor','k','LineWidth',1)

    % Plot Measurement
    scatter(iT,P_meas(iT),40,'k','filled',...
        'MarkerEdgeColor','k','Marker','x','LineWidth',2)
    
end
legend({'Prior','Posterior','Estimate','Measurement'})
ylim(pow_lim)
xlim([0,length(P_meas)+1])
ylabel('Power Generated (MW)')
xlabel('Turbine')



end

